version: "3.3"

services:
    api-adapter:
        build:
            context: .
        ports:
            - 8081:8081
            - 8082:8082
        restart: always
    ipfs:
        image: ipfs/kubo
        ports:
            - 5001:5001
        volumes:
            - ipfs-export:/export
            - ipfs-data:/data/ipfs
volumes:
    ipfs-export:
    ipfs-data:
